import io
import json
import time
from datetime import datetime

from fastapi import APIRouter
from fastapi.responses import StreamingResponse

try:
    from ..schemas import ExportRequest
except Exception:
    from schemas import ExportRequest  # type: ignore


router = APIRouter(tags=["Export"])


@router.post("/export/json")
async def export_json(request: ExportRequest):
    """Export scan results as JSON file."""
    export_data = {
        "tool": "Secret Guardian",
        "version": "1.0.0",
        "exported_at": datetime.now().isoformat(),
        "repository": request.repo_url,
        "scan_duration_seconds": request.scan_duration,
        "total_findings": len(request.findings),
        "severity_breakdown": request.severity_breakdown,
        "findings": request.findings,
        "disclaimer": "This report is for informational purposes only. Secrets should be rotated immediately.",
    }

    json_str = json.dumps(export_data, indent=2)

    return StreamingResponse(
        io.BytesIO(json_str.encode()),
        media_type="application/json",
        headers={
            "Content-Disposition": f"attachment; filename=secret-guardian-report-{int(time.time())}.json"
        },
    )


@router.post("/export/summary")
async def export_summary(request: ExportRequest):
    """Generate a text summary of scan results for clipboard copying."""
    severity = request.severity_breakdown

    summary_lines = [
        "=" * 50,
        "🛡️ SECRET GUARDIAN - SCAN REPORT",
        "=" * 50,
        f"Repository: {request.repo_url}",
        f"Scan Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"Duration: {request.scan_duration:.2f}s",
        "",
        "📊 SUMMARY",
        "-" * 30,
        f"Total Findings: {len(request.findings)}",
        f"  🔴 Critical: {severity.get('CRITICAL', 0)}",
        f"  🟠 High: {severity.get('HIGH', 0)}",
        f"  🟡 Medium: {severity.get('MEDIUM', 0)}",
        f"  🟢 Low: {severity.get('LOW', 0)}",
        "",
    ]

    if request.findings:
        summary_lines.append("📋 FINDINGS BY FILE")
        summary_lines.append("-" * 30)

        files: dict = {}
        for finding in request.findings:
            file_path = finding.get("file_path", "Unknown")
            if file_path not in files:
                files[file_path] = []
            files[file_path].append(finding)

        for file_path, file_findings in files.items():
            summary_lines.append(f"\\n📄 {file_path}")
            for finding in file_findings:
                severity_emoji = {
                    "CRITICAL": "🔴",
                    "HIGH": "🟠",
                    "MEDIUM": "🟡",
                    "LOW": "🟢",
                }.get(finding.get("severity", "LOW"), "⚪")
                summary_lines.append(
                    f"  {severity_emoji} Line {finding.get('line_number', '?')}: "
                    f"{finding.get('secret_type', 'Unknown')}"
                )

    summary_lines.extend(
        [
            "",
            "=" * 50,
            "⚠️ IMPORTANT: Rotate all exposed secrets immediately!",
            "Generated by Secret Guardian - https://github.com/secret-guardian",
        ]
    )

    return {"summary": "\\n".join(summary_lines)}
